version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/code
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
    - 9200:9200
    environment:
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"