version: '3'
services:
  web:
    build: .
    ports:
    - "5000:8080"
    volumes:
    - .:/code
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
    - 9200:9200